import { NgModule } from '@angular/core';
import {
  MatIconModule,
  MatDialogModule,
  MatButtonModule,
  MatTabsModule,
  MatStepperModule,
  MatFormFieldModule,
  MatInputModule,
  MatGridListModule,
  MatSelectModule,
  MatCheckboxModule,
  MatProgressSpinnerModule,
  MatDatepickerModule,
  MatNativeDateModule,
  MatSnackBarModule,
  MatRadioModule,
  MatToolbarModule,
  MatMenuModule,
  MatDividerModule,
  MatSlideToggleModule,
  MatDialogRef,
  MAT_DIALOG_DATA,
  MatTableModule,
  MatSidenavModule,
  MatListModule,
  MatPaginatorModule,
} from '@angular/material';

const MaterialComponents = [
  MatGridListModule,
  MatButtonModule,
  MatTabsModule,
  MatStepperModule,
  MatFormFieldModule,
  MatInputModule,
  MatSelectModule,
  MatCheckboxModule,
  MatButtonModule,
  MatPaginatorModule,
  MatProgressSpinnerModule,
  MatDialogModule,
  MatDatepickerModule,
  MatNativeDateModule,
  MatSnackBarModule,
  MatIconModule,
  MatRadioModule,
  MatToolbarModule,
  MatMenuModule,
  MatDividerModule,
  MatSlideToggleModule,
  MatTableModule,
  MatSidenavModule,
  MatListModule,
];

@NgModule({
  imports: [MaterialComponents],
  exports: [MaterialComponents],
  providers: [
    { provide: MatDialogRef, useValue: {} },
    { provide: MAT_DIALOG_DATA, useValue: [] },
  ],
})
export class MaterialModule {}
